const liMenu = [
    { id: 1, title: "پیشخوان", link: "/" },
    { id: 2, title: "کاربران", link: "users" },
    { id: 3, title: "گزارشات", link: "/gozareshat" },
    { id: 4, title: "کد های تخفیف", link: "/offers" },
    { id: 5, title: "تیکت ها", link: "/tikets" },
    { id: 6, title: "محصولات ما", link: "InventoryBox" },
];
const dataDashboardMain = [
    { id: 1, title: "مجموع فروش امروز", count: 32_850_000, percent: 15 },
    { id: 1, title: "تعداد محصولات", count: 56, percent: -30 },
    { id: 2, title: "کابران امروز", count: 25, percent: 37 },
    { id: 3, title: "بازدید امروز", count: 329, percent: 48 },
];
const users = [
    { id: 1, name: "مبین", email: "mobin@example.com", role: 1 },
    { id: 2, name: "سارا", email: "sara@example.com", role: 1 },
    { id: 3, name: "علی", email: "ali@example.com", role: 1 },
    { id: 4, name: "ریحانه", email: "reyhaneh@example.com", role: 1 },
    { id: 5, name: "امیر", email: "amir@example.com", role: 1 },
    { id: 6, name: "زهرا", email: "zahra@example.com", role: 0 },
    { id: 7, name: "حسین", email: "hossein@example.com", role: 0 },
    { id: 8, name: "مهدی", email: "mahdi@example.com", role: 0 },
    { id: 9, name: "نگار", email: "negar@example.com", role: 0 },
    { id: 10, name: "پارسا", email: "parsa@example.com", role: 0 },
    { id: 11, name: "نازنین", email: "nazanin@example.com", role: 0 },
    { id: 12, name: "علیرضا", email: "alireza@example.com", role: 0 },
    { id: 13, name: "فاطمه", email: "fatemeh@example.com", role: 0 },
    { id: 14, name: "رضا", email: "reza@example.com", role: 0 },
    { id: 15, name: "مینا", email: "mina@example.com", role: 0 },
    { id: 16, name: "نیما", email: "nima@example.com", role: 0 },
    { id: 17, name: "شایان", email: "shayan@example.com", role: 0 },
    { id: 18, name: "الهام", email: "elham@example.com", role: 0 },
    { id: 19, name: "بابک", email: "babak@example.com", role: 0 },
    { id: 20, name: "مریم", email: "maryam@example.com", role: 0 },
    { id: 21, name: "سامان", email: "saman@example.com", role: 0 },
    { id: 22, name: "سحر", email: "sahar@example.com", role: 0 },
    { id: 23, name: "پویا", email: "pooya@example.com", role: 0 },
    { id: 24, name: "رها", email: "raha@example.com", role: 0 },
    { id: 25, name: "فرزاد", email: "farzad@example.com", role: 0 },
    { id: 26, name: "نیلوفر", email: "niloufar@example.com", role: 0 },
    { id: 27, name: "حمید", email: "hamid@example.com", role: 0 },
    { id: 28, name: "آرمان", email: "arman@example.com", role: 0 },
    { id: 29, name: "بهناز", email: "behnaz@example.com", role: 0 },
    { id: 30, name: "کریم", email: "karim@example.com", role: 0 },
    { id: 31, name: "لیلا", email: "leila@example.com", role: 0 },
    { id: 32, name: "مژگان", email: "mojgan@example.com", role: 0 },
    { id: 33, name: "فرهاد", email: "farhad@example.com", role: 0 },
    { id: 34, name: "آتنا", email: "atena@example.com", role: 0 },
    { id: 35, name: "سامیار", email: "samyar@example.com", role: 0 },
    { id: 36, name: "نرگس", email: "narges@example.com", role: 0 },
    { id: 37, name: "امید", email: "omid@example.com", role: 0 },
    { id: 38, name: "شیرین", email: "shirin@example.com", role: 0 },
    { id: 39, name: "مهران", email: "mehran@example.com", role: 0 },
    { id: 40, name: "نازنین", email: "nazanin2@example.com", role: 0 }
];
export { liMenu, dataDashboardMain, users };
